name: XCS231N
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - notebook=7.3.2
  - h5py=3.12.1
  - imageio=2.37.0
  - ipython=9.1.0
  - json5=0.9.25
  - matplotlib=3.10.0
  - pillow=11.1.0
  - future=1.0.0
  - cython=3.0.11
  - scipy=1.15.3
  - pandas=2.3.1
  - tqdm=4.67.1
  - scikit-learn=1.7.1
  - pip=25.1
  - pip:
    - "--find-links https://download.pytorch.org/whl/torch/"
    - torch==2.7.1; sys_platform != "linux" and sys_platform != "win32"
    - torch==2.7.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - "--find-links https://download.pytorch.org/whl/torchvision/"
    - torchvision==0.22.1; sys_platform != "linux" and sys_platform != "win32"
    - torchvision==0.22.1+cpu; sys_platform == "linux" or sys_platform == "win32"
    - git+https://github.com/openai/CLIP.git
    - ftfy==6.3.1
    - regex==2024.11.6
    - thop==0.1.1-2209072238
    # required by tensorflow
    - numpy==2.1.3
    - tensorflow==2.19.0
    - tensorflow_datasets==4.9.9
    - opencv-python==4.12.0.88
